from celery import Celery

celery_app = Celery(
    "tasks",
    backend="redis://redis",
    broker="redis://redis:6379/0",
    include=[
        "server.plugins.abuseipdb",
        "server.plugins.basic_ip",
        # "server.plugins.binaryedge",
        # "server.plugins.botscout",
        "server.plugins.diario",
        "server.plugins.dns",
        "server.plugins.emailrep",
        "server.plugins.geoip",
        "server.plugins.haveibeenpwned",
        "server.plugins.hunterio",
        "server.plugins.maltiverse",
        "server.plugins.onyphe",
        # "server.plugins.otx",
        "server.plugins.pastebin",
        "server.plugins.phishtank",
        "server.plugins.robtex",
        "server.plugins.sherlock",
        "server.plugins.shodan",
        "server.plugins.tacyt",
        "server.plugins.threatcrowd",
        "server.plugins.threatminer",
        "server.plugins.urlscan",
        "server.plugins.verifymail",
        "server.plugins.virustotal",
        "server.plugins.vt_domain",
        "server.plugins.whois",
    ],
)
